language: java
dist: trusty
sudo: required
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
install: true
script:
  - "./gradlew build"
after_success:
  - "./gradlew jacocoTestReport coveralls"
